id: P009615
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN2131
  title: བརྒྱད་ཟིལ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    19033ed4be0e48c391ba0a993c609a09:
      image_group_id: I3CN2135
      title: ''
      volume_number: 1
      total_pages: 78
      base_file: v001.txt
